name: Publish to npm

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: '24'

      - run: pnpm install --frozen-lockfile

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # required for provenance\
      contents: read
    steps:
      - uses: actions/checkout@v6

#      - uses: pnpm/action-setup@v5
#        with:
#          version: 10

#      - uses: actions/setup-node@v6
#        with:
#          node-version: '24'

#      - run: pnpm install -g npm@latest

      - uses: flare-foundation/npm-release-action@add-action
        with:
          npm_access: public
          dry_run: false
